print("Hello world")
print("I am learning pythone")
print ("Those are my notes for - Automate the Boring Stuff with Python book")
print("")

print("Standard math operations")
a = (2 + 5)
print ("a = 2 + 5, a=", a)
b = (2 - 5)
print ("b = 2 - 5, b=", b)
c = (2 * 5.0)
print ("c = 2 * 5, c=", c)
d = (2 + 3 * 6)
print ("d = 2 + 3 * 6, d=", d)
e = ((2 + 3) * 6)
print ("e = (2 + 3) * 6, e=", e)
f = ((5 - 1) * ((7 + 1) / (3 - 1)))
print ("f = (5 - 1) * ((7 + 1) / (3 - 1)), f=", f)
g = (2 ** 5)
print ("g = 2 ** 5, g=", g)
print("** works as an exponentiation operator, in simple math it can be as ^ but in python, the sign ^ is used for another operation.")
print("")

print("Let's see advanced math operations")
h = (25 / 7)
print ("h = 25 / 7, h=", h)
i = (25 // 7)
print ("i = 25 // 7, i=", i)
j = (25 % 7)
print ("j = 25 % 7, j=", j)
print(" ")
print("What does // do.")
print("To get the final results the calculations are following 25 = 7 + 7 + 7 + 4 = 3 * 7 + 1 * 4, so the latgest integer is 3 and the remaining value is 4.")
print("// is floor division that is a normal division operation except that it returns the largest possible integer. This integer is either less than or equal to the normal division result.")
print("Thus the exponentiation evaluates to", i, "not", h, ".")
print(" ")
print("What does % do.")
print("To get the final results the calculations are following 25 = 7 + 7 + 7 + 4 = 3 * 7 + 1 * 4, so the latgest integer is 3 and the remaining value is 4.")
print("% is reminder or modulus operator that is a integer division operation except that it returns the reminder integer.")
print("Thus the exponentiation evaluates to", j, "not", h-i, ".")
print(" ")
#operationes with string
print("Let's see operations with string value")
k = "IloveY" + "Mariam"
print("k = IloveY + Mariam, k=", k)
l = "IloveY" * 5
print("l = IloveY * 5, l=", l)
m = "IloveY" + "Mariam" * 3
print("m = IloveY + Mariam * 3, m=", m)
n = ("IloveY" + "Mariam") * 3
print("n = (IloveY + Mariam) * 3, n=", n)
print(" ")
